development:
  adapter: mysql2
  encoding: utf8
  host: ganon.imagemanagement.com
  database: stocker
  username: stocker
  password: vo-hy-jugh-waf

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kozak_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  host: ganon.imagemanagement.com
  database: stocker
  username: stocker
  password: vo-hy-jugh-waf
