development:
  adapter: mysql2
  encoding: utf8
  host: 
  database: stocker
  username: stocker
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kozak_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  host: 
  database: stocker
  username: stocker
  password: 
